# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 15:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='age',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='unique_id',
            field=models.CharField(blank=True, max_length=25),
        ),
    ]
