# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-29 19:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_auto_20170629_1310'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='last_name',
            new_name='maiden_name',
        ),
    ]
